### ISSUE TITLE
skrrrahh(0) returns error

### ISSUE THREAD

**Issue by thmcmahon** [brooke-watson/BRRR#1]
When I call skrrrahh(0) I get the following error.

```{r}
Warning message:
In value[[3L]](cond) :
  beep() could not play the sound due to the following error:
Error in load.wave(fname): invalid file name
```

However all the sounds work as I looped through them all and they played.

I'm using R 3.4.2 on MacOS 10.13.1

**Comment by brooke-watson** [comment]
should be sorted, but let me know if it's still throwing errors. thanks for the heads up!

**Comment by thmcmahon** [comment]
Yep works now cheers.
