### ISSUE TITLE
Is the 7th sound clip Chinese? 

### ISSUE THREAD

**Issue by JackieMium** [brooke-watson/BRRR#8]
I am from China and I speak Chinese. I used `beepr` for a long time and tried `BRRR` only few days ago. 
The 7th clip (`skrrrahh(7)`)  in `BRRR` sounds really like Chinese, which means 'Good or Finished', only that the pronunciation is really award. If it is indeed Chinese, I really hope you can use a clip from a native speaker that sounds natural. I don't think it is hard to find that on the Internet. Or if it is hard for you, let me know and I will see what I can do. 
Hope this is not offensive to raise a question like this.

**Comment by jletienne** [comment]
It's Big Sean, the sound clip is the phrase "Hold Up" from the song GUAP

**Comment by JackieMium** [comment]
@jletienne My fault, sorry.:joy:

**Comment by jletienne** [comment]
@JackieMium no problem happy to help 👍

**Comment by brooke-watson** [comment]
This is amazing. Thanks for offering to help!
